# config.yaml
input_dir: data/lris2_flats
output_dir: output

# Set to true to start Prefect UI (at http://127.0.0.1:4200)
use_prefect_server: true

# Set to true to also save corrected flat images (flat_corrected.fits)
save_corrected_flat: true

# Number of files to process in parallel
max_workers: 2
